[theme]
# Primary button/accent color: SWAN WING
primaryColor="#F5F0E9" 

# Background color of the main page: ROYAL BLUE
backgroundColor="#112250" 

# Background color of the sidebar and containers: SAPPHIRE 
secondaryBackgroundColor="#3C507D" 

# Color used for ALL standard text: QUICKSAND
textColor="#E0C58F" 

# 폰트 계열을 셰리프(serif)로 설정
font="serif"
