[theme]
# Primary button/accent color: ROYAL BLUE
primaryColor="#112250" 

# Background color of the main page: SAPPHIRE
backgroundColor="#3C507D" 

# Background color of the sidebar and headers: SHELLSTONE 
secondaryBackgroundColor="#D9CBC2" 

# Color used for text: QUICKSAND
textColor="#E0C58F" 

# Font family
font="sans serif"
